/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostId = IDL.Nat;
export const ApiError = IDL.Variant({
  'alreadyExists' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Null,
  'selfAction' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : ApiError });
export const Result_1 = IDL.Variant({ 'ok' : PostId, 'err' : ApiError });
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const User = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'followers' : IDL.Vec(UserId),
  'following' : IDL.Vec(UserId),
  'profilePicture' : IDL.Text,
});
export const CommentId = IDL.Nat;
export const Comment = IDL.Record({
  'id' : CommentId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'user' : UserId,
});
export const Post = IDL.Record({
  'id' : PostId,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'user' : UserId,
  'likes' : IDL.Vec(UserId),
  'image' : IDL.Opt(IDL.Text),
  'comments' : IDL.Vec(Comment),
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func([PostId, IDL.Text], [Result], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Result_1], []),
  'deletePost' : IDL.Func([PostId], [Result], []),
  'followUser' : IDL.Func([UserId], [Result], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getExplorePosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(User)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(User)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'likePost' : IDL.Func([PostId], [Result], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'unfollowUser' : IDL.Func([UserId], [Result], []),
  'unlikePost' : IDL.Func([PostId], [Result], []),
  'updatePost' : IDL.Func([PostId, IDL.Text, IDL.Opt(IDL.Text)], [Result], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostId = IDL.Nat;
  const ApiError = IDL.Variant({
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Null,
    'selfAction' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : ApiError });
  const Result_1 = IDL.Variant({ 'ok' : PostId, 'err' : ApiError });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const User = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'followers' : IDL.Vec(UserId),
    'following' : IDL.Vec(UserId),
    'profilePicture' : IDL.Text,
  });
  const CommentId = IDL.Nat;
  const Comment = IDL.Record({
    'id' : CommentId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'user' : UserId,
  });
  const Post = IDL.Record({
    'id' : PostId,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'user' : UserId,
    'likes' : IDL.Vec(UserId),
    'image' : IDL.Opt(IDL.Text),
    'comments' : IDL.Vec(Comment),
  });
  
  return IDL.Service({
    'addComment' : IDL.Func([PostId, IDL.Text], [Result], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Result_1], []),
    'deletePost' : IDL.Func([PostId], [Result], []),
    'followUser' : IDL.Func([UserId], [Result], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getExplorePosts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getFollowers' : IDL.Func([UserId], [IDL.Vec(User)], ['query']),
    'getFollowing' : IDL.Func([UserId], [IDL.Vec(User)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'likePost' : IDL.Func([PostId], [Result], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'unfollowUser' : IDL.Func([UserId], [Result], []),
    'unlikePost' : IDL.Func([PostId], [Result], []),
    'updatePost' : IDL.Func(
        [PostId, IDL.Text, IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };