/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApiError = { 'alreadyExists' : null } |
  { 'invalidInput' : string } |
  { 'notFound' : null } |
  { 'selfAction' : null } |
  { 'unauthorized' : null };
export interface Comment {
  'id' : CommentId,
  'createdAt' : Timestamp,
  'text' : string,
  'user' : UserId,
}
export type CommentId = bigint;
export interface Post {
  'id' : PostId,
  'content' : string,
  'createdAt' : Timestamp,
  'user' : UserId,
  'likes' : Array<UserId>,
  'image' : [] | [string],
  'comments' : Array<Comment>,
}
export type PostId = bigint;
export type Result = { 'ok' : null } |
  { 'err' : ApiError };
export type Result_1 = { 'ok' : PostId } |
  { 'err' : ApiError };
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'bio' : string,
  'username' : string,
  'createdAt' : Timestamp,
  'followers' : Array<UserId>,
  'following' : Array<UserId>,
  'profilePicture' : string,
}
export type UserId = Principal;
export interface _SERVICE {
  'addComment' : ActorMethod<[PostId, string], Result>,
  'createPost' : ActorMethod<[string, [] | [string]], Result_1>,
  'deletePost' : ActorMethod<[PostId], Result>,
  'followUser' : ActorMethod<[UserId], Result>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getExplorePosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getFeed' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getFollowers' : ActorMethod<[UserId], Array<User>>,
  'getFollowing' : ActorMethod<[UserId], Array<User>>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getPost' : ActorMethod<[PostId], [] | [Post]>,
  'getUser' : ActorMethod<[UserId], [] | [User]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [User]>,
  'likePost' : ActorMethod<[PostId], Result>,
  'registerUser' : ActorMethod<[string, string, string], Result>,
  'unfollowUser' : ActorMethod<[UserId], Result>,
  'unlikePost' : ActorMethod<[PostId], Result>,
  'updatePost' : ActorMethod<[PostId, string, [] | [string]], Result>,
  'updateProfile' : ActorMethod<[string, string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];